//go:build !ignore_autogenerated

// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/GoogleCloudPlatform/k8s-config-connector/apis/refs/v1beta1"
	k8sv1alpha1 "github.com/GoogleCloudPlatform/k8s-config-connector/pkg/apis/k8s/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateManagerTrustConfigRef) DeepCopyInto(out *CertificateManagerTrustConfigRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateManagerTrustConfigRef.
func (in *CertificateManagerTrustConfigRef) DeepCopy() *CertificateManagerTrustConfigRef {
	if in == nil {
		return nil
	}
	out := new(CertificateManagerTrustConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityGatewaySecurityPolicy) DeepCopyInto(out *NetworkSecurityGatewaySecurityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityGatewaySecurityPolicy.
func (in *NetworkSecurityGatewaySecurityPolicy) DeepCopy() *NetworkSecurityGatewaySecurityPolicy {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityGatewaySecurityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkSecurityGatewaySecurityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityGatewaySecurityPolicyList) DeepCopyInto(out *NetworkSecurityGatewaySecurityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkSecurityGatewaySecurityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityGatewaySecurityPolicyList.
func (in *NetworkSecurityGatewaySecurityPolicyList) DeepCopy() *NetworkSecurityGatewaySecurityPolicyList {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityGatewaySecurityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkSecurityGatewaySecurityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityGatewaySecurityPolicyObservedState) DeepCopyInto(out *NetworkSecurityGatewaySecurityPolicyObservedState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityGatewaySecurityPolicyObservedState.
func (in *NetworkSecurityGatewaySecurityPolicyObservedState) DeepCopy() *NetworkSecurityGatewaySecurityPolicyObservedState {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityGatewaySecurityPolicyObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityGatewaySecurityPolicyRef) DeepCopyInto(out *NetworkSecurityGatewaySecurityPolicyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityGatewaySecurityPolicyRef.
func (in *NetworkSecurityGatewaySecurityPolicyRef) DeepCopy() *NetworkSecurityGatewaySecurityPolicyRef {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityGatewaySecurityPolicyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityGatewaySecurityPolicyRule) DeepCopyInto(out *NetworkSecurityGatewaySecurityPolicyRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityGatewaySecurityPolicyRule.
func (in *NetworkSecurityGatewaySecurityPolicyRule) DeepCopy() *NetworkSecurityGatewaySecurityPolicyRule {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityGatewaySecurityPolicyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkSecurityGatewaySecurityPolicyRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityGatewaySecurityPolicyRuleList) DeepCopyInto(out *NetworkSecurityGatewaySecurityPolicyRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkSecurityGatewaySecurityPolicyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityGatewaySecurityPolicyRuleList.
func (in *NetworkSecurityGatewaySecurityPolicyRuleList) DeepCopy() *NetworkSecurityGatewaySecurityPolicyRuleList {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityGatewaySecurityPolicyRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkSecurityGatewaySecurityPolicyRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityGatewaySecurityPolicyRuleObservedState) DeepCopyInto(out *NetworkSecurityGatewaySecurityPolicyRuleObservedState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityGatewaySecurityPolicyRuleObservedState.
func (in *NetworkSecurityGatewaySecurityPolicyRuleObservedState) DeepCopy() *NetworkSecurityGatewaySecurityPolicyRuleObservedState {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityGatewaySecurityPolicyRuleObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityGatewaySecurityPolicyRuleRef) DeepCopyInto(out *NetworkSecurityGatewaySecurityPolicyRuleRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityGatewaySecurityPolicyRuleRef.
func (in *NetworkSecurityGatewaySecurityPolicyRuleRef) DeepCopy() *NetworkSecurityGatewaySecurityPolicyRuleRef {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityGatewaySecurityPolicyRuleRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityGatewaySecurityPolicyRuleSpec) DeepCopyInto(out *NetworkSecurityGatewaySecurityPolicyRuleSpec) {
	*out = *in
	if in.GatewaySecurityPolicyRef != nil {
		in, out := &in.GatewaySecurityPolicyRef, &out.GatewaySecurityPolicyRef
		*out = new(NetworkSecurityGatewaySecurityPolicyRef)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityGatewaySecurityPolicyRuleSpec.
func (in *NetworkSecurityGatewaySecurityPolicyRuleSpec) DeepCopy() *NetworkSecurityGatewaySecurityPolicyRuleSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityGatewaySecurityPolicyRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityGatewaySecurityPolicyRuleStatus) DeepCopyInto(out *NetworkSecurityGatewaySecurityPolicyRuleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]k8sv1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(NetworkSecurityGatewaySecurityPolicyRuleObservedState)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityGatewaySecurityPolicyRuleStatus.
func (in *NetworkSecurityGatewaySecurityPolicyRuleStatus) DeepCopy() *NetworkSecurityGatewaySecurityPolicyRuleStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityGatewaySecurityPolicyRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityGatewaySecurityPolicySpec) DeepCopyInto(out *NetworkSecurityGatewaySecurityPolicySpec) {
	*out = *in
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1beta1.ProjectRef)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.TlsInspectionPolicyRef != nil {
		in, out := &in.TlsInspectionPolicyRef, &out.TlsInspectionPolicyRef
		*out = new(NetworkSecurityTLSInspectionPolicyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityGatewaySecurityPolicySpec.
func (in *NetworkSecurityGatewaySecurityPolicySpec) DeepCopy() *NetworkSecurityGatewaySecurityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityGatewaySecurityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityGatewaySecurityPolicyStatus) DeepCopyInto(out *NetworkSecurityGatewaySecurityPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]k8sv1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(NetworkSecurityGatewaySecurityPolicyObservedState)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityGatewaySecurityPolicyStatus.
func (in *NetworkSecurityGatewaySecurityPolicyStatus) DeepCopy() *NetworkSecurityGatewaySecurityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityGatewaySecurityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityTLSInspectionPolicy) DeepCopyInto(out *NetworkSecurityTLSInspectionPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityTLSInspectionPolicy.
func (in *NetworkSecurityTLSInspectionPolicy) DeepCopy() *NetworkSecurityTLSInspectionPolicy {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityTLSInspectionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkSecurityTLSInspectionPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityTLSInspectionPolicyList) DeepCopyInto(out *NetworkSecurityTLSInspectionPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkSecurityTLSInspectionPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityTLSInspectionPolicyList.
func (in *NetworkSecurityTLSInspectionPolicyList) DeepCopy() *NetworkSecurityTLSInspectionPolicyList {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityTLSInspectionPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkSecurityTLSInspectionPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityTLSInspectionPolicyObservedState) DeepCopyInto(out *NetworkSecurityTLSInspectionPolicyObservedState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityTLSInspectionPolicyObservedState.
func (in *NetworkSecurityTLSInspectionPolicyObservedState) DeepCopy() *NetworkSecurityTLSInspectionPolicyObservedState {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityTLSInspectionPolicyObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityTLSInspectionPolicyRef) DeepCopyInto(out *NetworkSecurityTLSInspectionPolicyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityTLSInspectionPolicyRef.
func (in *NetworkSecurityTLSInspectionPolicyRef) DeepCopy() *NetworkSecurityTLSInspectionPolicyRef {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityTLSInspectionPolicyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityTLSInspectionPolicySpec) DeepCopyInto(out *NetworkSecurityTLSInspectionPolicySpec) {
	*out = *in
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1beta1.ProjectRef)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.CaPoolRef != nil {
		in, out := &in.CaPoolRef, &out.CaPoolRef
		*out = new(v1beta1.PrivateCACAPoolRef)
		**out = **in
	}
	if in.TrustConfigRef != nil {
		in, out := &in.TrustConfigRef, &out.TrustConfigRef
		*out = new(CertificateManagerTrustConfigRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityTLSInspectionPolicySpec.
func (in *NetworkSecurityTLSInspectionPolicySpec) DeepCopy() *NetworkSecurityTLSInspectionPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityTLSInspectionPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityTLSInspectionPolicyStatus) DeepCopyInto(out *NetworkSecurityTLSInspectionPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]k8sv1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(NetworkSecurityTLSInspectionPolicyObservedState)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityTLSInspectionPolicyStatus.
func (in *NetworkSecurityTLSInspectionPolicyStatus) DeepCopy() *NetworkSecurityTLSInspectionPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityTLSInspectionPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityUrlList) DeepCopyInto(out *NetworkSecurityUrlList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityUrlList.
func (in *NetworkSecurityUrlList) DeepCopy() *NetworkSecurityUrlList {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityUrlList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkSecurityUrlList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityUrlListList) DeepCopyInto(out *NetworkSecurityUrlListList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkSecurityUrlList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityUrlListList.
func (in *NetworkSecurityUrlListList) DeepCopy() *NetworkSecurityUrlListList {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityUrlListList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkSecurityUrlListList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityUrlListObservedState) DeepCopyInto(out *NetworkSecurityUrlListObservedState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityUrlListObservedState.
func (in *NetworkSecurityUrlListObservedState) DeepCopy() *NetworkSecurityUrlListObservedState {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityUrlListObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityUrlListRef) DeepCopyInto(out *NetworkSecurityUrlListRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityUrlListRef.
func (in *NetworkSecurityUrlListRef) DeepCopy() *NetworkSecurityUrlListRef {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityUrlListRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityUrlListSpec) DeepCopyInto(out *NetworkSecurityUrlListSpec) {
	*out = *in
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1beta1.ProjectRef)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityUrlListSpec.
func (in *NetworkSecurityUrlListSpec) DeepCopy() *NetworkSecurityUrlListSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityUrlListSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityUrlListStatus) DeepCopyInto(out *NetworkSecurityUrlListStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]k8sv1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(NetworkSecurityUrlListObservedState)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityUrlListStatus.
func (in *NetworkSecurityUrlListStatus) DeepCopy() *NetworkSecurityUrlListStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityUrlListStatus)
	in.DeepCopyInto(out)
	return out
}
