import json
import sys
import os

def run_cmd(cmd):
    return os.popen(cmd).read().strip()

with open('all_issues.json') as f:
    issues = json.load(f)

# The candidates were generated by find_candidates_dcl2crd.py
candidates_raw = run_cmd("python3 find_candidates_dcl2crd.py").split('\n')
candidates = [c.split(' ') for c in candidates_raw if c]

# Determine pending issues for THIS task
# Pending issues are OPEN issues with the title matching "Create generate.sh and types.go files for"
open_issues = [i for i in issues if i['state'] == 'OPEN' and 'Create generate.sh and types.go files for' in i['title']]
pending_count = len(open_issues)
print(f"Pending issues found: {pending_count}")

# Check candidates against existing issues
issue_created = False
for group, kind in candidates:
    expected_title_suffix = f"for {group} {kind}".lower()
    matching_issues = [i for i in issues if i['title'].lower().endswith(expected_title_suffix)]
    
    if matching_issues:
        issue = matching_issues[0]
        # Check labels
        current_labels = [l['name'] for l in issue['labels']]
        required_labels = ['overseer', 'area/direct', 'priority/medium']
        missing_labels = [l for l in required_labels if l not in current_labels]
        if missing_labels:
            print(f"Injecting labels {missing_labels} for issue #{issue['number']}")
            run_cmd(f"gh issue edit {issue['number']} --add-label '{','.join(missing_labels)}'")
    else:
        # No issue exists
        if not issue_created:
            if pending_count >= 10:
                print("More than 10 pending issues already exist. Skipping creating new ones to avoid overwhelming the team.")
                # We do not create a new issue, but we still continue checking labels for existing ones
                issue_created = True # Pretend we created one so we don't try again
            else:
                print(f"Creating new issue for {group} {kind}")
                # We will output this decision so the main bot can run the creation logic
                # For now, let's just print it and we will do it from the shell or python
                print(f"TARGET_NEW_ISSUE={group} {kind}")
                issue_created = True

