// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by "scripts/generate-gvks" in "make manifests"; DO NOT EDIT.

package supportedgvks

import "k8s.io/apimachinery/pkg/runtime/schema"

type legacyGVKData struct {
	Terraform bool
	DCL       bool
}

var legacyGVKs = map[schema.GroupVersionKind]legacyGVKData{
	{
		Group:   "accesscontextmanager.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "AccessContextManagerAccessLevel",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "accesscontextmanager.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "AccessContextManagerAccessPolicy",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "alloydb.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "AlloyDBBackup",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "alloydb.cnrm.cloud.google.com",
		Version: "v1alpha1",
		Kind:    "AlloyDBBackup",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "alloydb.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "AlloyDBCluster",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "alloydb.cnrm.cloud.google.com",
		Version: "v1alpha1",
		Kind:    "AlloyDBCluster",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "apigee.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "ApigeeEnvironment",
	}: {
		Terraform: false,
		DCL:       true,
	},
	{
		Group:   "apigee.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "ApigeeOrganization",
	}: {
		Terraform: false,
		DCL:       true,
	},
	{
		Group:   "apikeys.cnrm.cloud.google.com",
		Version: "v1alpha1",
		Kind:    "APIKeysKey",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "artifactregistry.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "ArtifactRegistryRepository",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "bigquery.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "BigQueryDataset",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "bigquery.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "BigQueryTable",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "bigtable.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "BigtableAppProfile",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "bigtable.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "BigtableInstance",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "bigtable.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "BigtableTable",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "compute.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "ComputeForwardingRule",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "compute.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "ComputeSecurityPolicy",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "compute.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "ComputeSubnetwork",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "compute.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "ComputeTargetTCPProxy",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "containerattached.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "ContainerAttachedCluster",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "datacatalog.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "DataCatalogPolicyTag",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "datacatalog.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "DataCatalogTaxonomy",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "dataflow.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "DataflowFlexTemplateJob",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "firestore.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "FirestoreIndex",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "iam.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "IAMServiceAccountKey",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "kms.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "KMSKeyRing",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "monitoring.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "MonitoringNotificationChannel",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "networksecurity.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "NetworkSecurityAuthorizationPolicy",
	}: {
		Terraform: false,
		DCL:       true,
	},
	{
		Group:   "privateca.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "PrivateCACAPool",
	}: {
		Terraform: false,
		DCL:       true,
	},
	{
		Group:   "run.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "RunJob",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "secretmanager.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "SecretManagerSecret",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "secretmanager.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "SecretManagerSecretVersion",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "serviceusage.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "ServiceIdentity",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "spanner.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "SpannerInstance",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "tags.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "TagsLocationTagBinding",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "tags.cnrm.cloud.google.com",
		Version: "v1alpha1",
		Kind:    "TagsLocationTagBinding",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "tags.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "TagsTagBinding",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "tags.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "TagsTagKey",
	}: {
		Terraform: true,
		DCL:       false,
	},
	{
		Group:   "tags.cnrm.cloud.google.com",
		Version: "v1beta1",
		Kind:    "TagsTagValue",
	}: {
		Terraform: true,
		DCL:       false,
	}}
